<a href="https://colab.research.google.com/github/sanjeeva2455/data-science/blob/main/hyperparameter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import pandas as pd

In [4]:
df =pd.read_csv('/content/diabetes.csv')

In [5]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [8]:
import numpy as np


In [9]:
df['Glucose'] = np.where(df['Glucose'] == 0, df['Glucose'].median(),df['Glucose'])
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6    148.0             72  ...                     0.627   50        1
1            1     85.0             66  ...                     0.351   31        0
2            8    183.0             64  ...                     0.672   32        1
3            1     89.0             66  ...                     0.167   21        0
4            0    137.0             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [11]:
x = df.drop('Outcome', axis = 1)
y = df['Outcome']

In [12]:
x

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6    148.0             72  ...  33.6                     0.627   50
1              1     85.0             66  ...  26.6                     0.351   31
2              8    183.0             64  ...  23.3                     0.672   32
3              1     89.0             66  ...  28.1                     0.167   21
4              0    137.0             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10    101.0             76  ...  32.9                     0.171   63
764            2    122.0             70  ...  36.8                     0.340   27
765            5    121.0             72  ...  26.2                     0.245   30
766            1    126.0             60  ...  30.1                     0.349   47
767            1     93.0             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [13]:
pd.DataFrame(x , columns= df.columns[:-1])

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6    148.0             72  ...  33.6                     0.627   50
1              1     85.0             66  ...  26.6                     0.351   31
2              8    183.0             64  ...  23.3                     0.672   32
3              1     89.0             66  ...  28.1                     0.167   21
4              0    137.0             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10    101.0             76  ...  32.9                     0.171   63
764            2    122.0             70  ...  36.8                     0.340   27
765            5    121.0             72  ...  26.2                     0.245   30
766            1    126.0             60  ...  30.1                     0.349   47
767            1     93.0             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [14]:
#Train Test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test  = train_test_split(x, y , test_size = 0.20, random_state = 0)

In [15]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators = 10).fit(x_train, y_train)
prediction = rf_classifier.predict(x_test)

In [16]:
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [17]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [18]:
print(confusion_matrix(y_test, prediction))
print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

[[96 11]
 [20 27]]
0.7987012987012987
              precision    recall  f1-score   support

           0       0.83      0.90      0.86       107
           1       0.71      0.57      0.64        47

    accuracy                           0.80       154
   macro avg       0.77      0.74      0.75       154
weighted avg       0.79      0.80      0.79       154



the hyper parameters used by random forest classifier are:

criterion : the function used to evaluate the quality of a split.

max_depth : max number of levels allowed in each tree

max_features : max no of features considered when splitting a node

min_samples_leaf = minimum number of samples which can be stored in a tree leaf.

min_sample_split = minimum number of samples necessary in a node to cause node 
splitting.

n_estimators = number of trees in the ensamble 

In [19]:
#manual Hyperparameter tuninig
model = RandomForestClassifier(n_estimators=300, criterion='entropy', max_features='sqrt',min_samples_leaf=10,random_state=100).fit(x_train, y_train)
predictions = model.predict(x_test)
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))

[[98  9]
 [18 29]]
0.8246753246753247
              precision    recall  f1-score   support

           0       0.84      0.92      0.88       107
           1       0.76      0.62      0.68        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154



Random Search CV

In [20]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV

#number of trees in Random Forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num=10)]

#num of featuresto be considered for every split
max_features = ['auto','sqrt','log2']

#max number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]

#min number of samples required to split a node
min_samples_split = [2,5,10,14]

# minimum number of samples required at each leaf node
min_samples_leaf = [1,2,4,6,8]

# create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features':max_features,
               'max_depth':max_depth,
               'min_samples_split':min_samples_split,
               'min_samples_leaf':min_samples_leaf,
               'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [21]:
rf = RandomForestClassifier()
rf_randomcv = RandomizedSearchCV(estimator=rf, param_distributions=random_grid, n_iter = 100, verbose= 2, random_state= 100 , n_jobs= -1, cv = 3)

#fit the randomized model
rf_randomcv.fit(x_train, y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  8.6min finished


RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [22]:
rf_randomcv.best_params_

{'criterion': 'gini',
 'max_depth': 10,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 14,
 'n_estimators': 2000}

In [23]:
rf_randomcv

RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [24]:
best_random_grid = rf_randomcv.best_estimator_

In [25]:
from sklearn.metrics import accuracy_score
y_pred = best_random_grid.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test, y_pred)))
print("Classification report: {}".format(classification_report(y_test, y_pred)))

[[97 10]
 [15 32]]
Accuracy Score 0.8376623376623377
Classification report:               precision    recall  f1-score   support

           0       0.87      0.91      0.89       107
           1       0.76      0.68      0.72        47

    accuracy                           0.84       154
   macro avg       0.81      0.79      0.80       154
weighted avg       0.83      0.84      0.83       154



GridSearch CV

In [26]:
rf_randomcv.best_params_

{'criterion': 'gini',
 'max_depth': 10,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 14,
 'n_estimators': 2000}

In [40]:
from sklearn.model_selection import  GridSearchCV
param_grid = {
    'criterion':[rf_randomcv.best_params_['criterion']],
    
    'max_depth':[rf_randomcv.best_params_['max_depth']],
    
    'max_features':[rf_randomcv.best_params_['max_features']],
    
    'min_samples_leaf': [rf_randomcv.best_params_['min_samples_leaf'], rf_randomcv.best_params_['min_samples_leaf'] + 2,rf_randomcv.best_params_['min_samples_leaf'] + 4],
    
    'min_samples_split' : [rf_randomcv.best_params_['min_samples_split'] - 2, rf_randomcv.best_params_['min_samples_split'] - 1, rf_randomcv.best_params_['min_samples_split'], rf_randomcv.best_params_['min_samples_split']+1, rf_randomcv.best_params_['min_samples_split']+2],

    'n_estimators' : [rf_randomcv.best_params_['n_estimators'] - 200, rf_randomcv.best_params_['n_estimators'] - 100, rf_randomcv.best_params_['n_estimators'], rf_randomcv.best_params_['n_estimators'] + 100, rf_randomcv.best_params_['n_estimators'] + 200]
    }
print(param_grid)

{'criterion': ['gini'], 'max_depth': [10], 'max_features': ['sqrt'], 'min_samples_leaf': [1, 3, 5], 'min_samples_split': [12, 13, 14, 15, 16], 'n_estimators': [1800, 1900, 2000, 2100, 2200]}


In [42]:
#fit the grid_search to the data
rf = RandomForestClassifier()
grid_search = GridSearchCV(estimator= rf, param_grid=param_grid, cv = 10, n_jobs = -1, verbose = 2)
grid_search.fit(x_train, y_train)

Fitting 10 folds for each of 75 candidates, totalling 750 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:  7.8min
[Parallel(n_jobs=-1)]: Done 361 tasks      | elapsed: 17.8min
[Parallel(n_jobs=-1)]: Done 644 tasks      | elapsed: 31.8min
[Parallel(n_jobs=-1)]: Done 750 out of 750 | elapsed: 37.1min finished


GridSearchCV(cv=10, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rand

In [43]:
grid_search.best_estimator_

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=12,
                       min_weight_fraction_leaf=0.0, n_estimators=2100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [44]:
best_grid = grid_search.best_estimator_

In [45]:
best_grid

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=12,
                       min_weight_fraction_leaf=0.0, n_estimators=2100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [48]:
y_pred = best_grid.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print("Accuracy Score{}".format(accuracy_score(y_test, y_pred)))
print("Classification repor : {}". format(classification_report(y_test, y_pred)))

[[97 10]
 [18 29]]
Accuracy Score0.8181818181818182
Classification repor :               precision    recall  f1-score   support

           0       0.84      0.91      0.87       107
           1       0.74      0.62      0.67        47

    accuracy                           0.82       154
   macro avg       0.79      0.76      0.77       154
weighted avg       0.81      0.82      0.81       154

